//Table Reducer Actions
export const ROW_CLICKED = "ROW_CLICKED";
export const SEARCH_ITEM_CLICKED = "SEARCH_ITEM_CLICKED";

//Navbar Reducer Actions
export const SEARCH_INPUT_CHANGE = "SEARCH_INPUT_CHANGE";
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";
export const CATEGORY_MODAL_OPEN = "CATEGORY_MODAL_OPEN";

//Dish Suggest Reducer

export const CHANGE_INGREDIENTS = "CHANGE_INGREDIENTS";
export const CLEAR_ALL_INGREDIENTS = "CLEAR_ALL_INGREDIENTS";
export const DELETE_INGREDIENTS = "DELETE_INGREDIENTS";
